version: "3.1"

networks:
  my-network:
    driver: bridge

services:
  nginx:
    container_name: my-nginx
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - ./src/frontend/dist/:/var/www/frontend/
      - ./src/backend/:/var/www/backend/
    ports:
      - 80:80
      - 443:443
    networks:
      - my-network
    depends_on:
      - node

  node:
    container_name: my-node
    build: 
      context: ./src/backend
      dockerfile: service-backend.Dockerfile
    ports:
      - 9400:9400
    networks:
      - my-network
    volumes: 
      - ./src/backend:/app
    depends_on:
      - db

  db:
    container_name: my-db
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - my-network
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - ./mysql/mysql:/var/lib/mysql

  phpmyadmin:
    container_name: my-phpmyadmin
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOSTS=db
      - PMA_PORT=3306
    ports:
      - 9501:80
    networks:
      - my-network
    depends_on: 
      - db